name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v5

      - uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npx prettier --check .

      - run: npm run lint

      - run: npm test

      - run: npm run prepublishOnly
